apiVersion: v1
kind: Service
metadata:
 labels:
   app: hello-ms
 name: hello-ms
namespace: default
spec:
 ports:
 - nodePort: 31500
   port: 80
   protocol: TCP
   targetPort: 80
 selector:
  app: hello-ms
 type: NodePort
